### ISSUE TITLE
Upgrade to Contao 4.7?

### ISSUE THREAD

**Issue by onemarshall** [jedoStyle/contao-testimonials#6]
Hi, would it be possible to update testimonials to work with Contao 4.7?
Thanks

**Comment by jedoCodes** [comment]
Yes. I'm already working on a successor to the extension. I still need some time for the development.

**Comment by onemarshall** [comment]
Ok, thanks. Do you have any plans for integration with Isotope?

**Comment by onemarshall** [comment]
-
